config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    # raise
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    if @pet.destroy
      redirect_to pets_path
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:colour, :species, :location, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKitty1872</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Change something about this <%= @pet.species %></h1>
  <%= simple_form_for @pet do |f| %>
    <%= f.input :species %>
    <%= f.input :colour %>
    <%= f.input :location %>
    <%= f.input :date %>
    <%= f.submit %>
  <% end %>
</div>

app/views/pets/index.html.erb
<div class="container mt-5">
  <h1>Found Pets</h1>
  <% @pets.each do |pet| %>
    <div class="card mb-3" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= pet.species %></h5>
<!--        <h6 class="card-subtitle mb-2 text-body-secondary">A <%#= pet.colour %> <%= pet.species %></h6>
        <p class="card-text">Was found at <%#= pet.location %> on <%= pet.date %>.</p>-->
        <%= link_to "more info", pet_path(pet) %>
        <%= link_to "remove", pet_path(pet), data: {turbo_method: :delete, turbo_confirm: "Serious;y???!"} %>
      </div>
    </div>
    <% end %>

  <%= link_to "Found a pet!", new_pet_path, class: "btn btn-primary" %>
  </div>

app/views/pets/new.html.erb
<div class="container">
  <h1>YAY! You found a pet!</h1>
  <p>Please add it's details</p>

    <%= simple_form_for @pet do |f| %>
      <%= f.input :species %>
      <%= f.input :colour %>
      <%= f.input :location %>
      <%= f.input :date %>
      <%= f.submit %>
  <% end %>

</div>

app/views/pets/show.html.erb
<div class="container mt-5">
  <h1>Someone found this <%= @pet.species %></h1>
  <h2>Where?</h2>
  <p>It was found in <%= @pet.location %>.</p>

  <h2>When?</h2>
  <p>It was found on <%= @pet.date.strftime('%A, %b %d') %> </p>


  <%= link_to "edit", edit_pet_path(@pet), class: "btn btn-danger"  %>

  <%= link_to "all pets", pets_path %>
</div>